from pathlib import Path
import json,csv,hashlib,math,datetime
from sx import page_graph,one,kids
F=Path(__file__).resolve().parents[1];R=F/'reports';V=F/'validation';E=F/'evidence';read=lambda p:json.loads(p.read_text(encoding='utf8'))
h=read(V/'frozen_sources.json')['source_pcb_sha256'];power=read(V/'POWER_voltage_and_resistance_review.json');r1=read(V/'PCB_R1_geometry_fixed_and_native.json');r2=read(V/'PCB_R2_actual_copper_and_returns.json');r3=read(V/'PCB_R3_system_assembly_thermal_support.json');man=read(V/'CONSISTENCY_R2_manufacturing.json');th=read(V/'THERMAL_six_paired_cases.json');mass=read(F/'mechanical/bare_PCB_support_analysis.json');micro=read(V/'MICRO_243_disposition.json');cad=read(F/'mechanical/geometry_validation.json');fault=read(V/'SCH_R3_dynamic_fault_and_rearm.json');pa=read(E/'candidate_placement_comparison.json');geo=read(V/'GEOMETRY_remaining_exceptions.json');paths=read(V/'routing/route_resistance_and_decoupling.json');ni=read(V/'routing/native_inventory.json');bp=read(E/'baseline/route_resistance_and_decoupling.json')
P=lambda s:{'type':'paragraph','text':s};T=lambda headers,rows,widths=None:{'type':'table','header':headers,'rows':rows,'widths':widths};I=lambda name,cap:{'type':'image','path':'figures/'+name+'.png','caption':cap};pages=[]
def add(title,*blocks):pages.append({'title':title,'blocks':list(blocks)})
fnum=lambda x,n=3:f'{x:.{n}f}'
base=power['paired_methods']['V3'];new=power['paired_methods']['V3.1'];sheet0=base['sheet_forward_ohm_20C_by_mesh']['0.04'];sheet1=new['sheet_forward_ohm_20C_by_mesh']['0.04'];pct=(1-sheet1/sheet0)*100
add('01  CurtainDrive V3.1｜交付状态',P('本轮完成离线工程与制造资料核验。样机电气、抗扰、温升、转矩、停止距离和完整固件运行验收尚未执行。采用当前磁盘 V3，完整备份后在独立副本修改；源工程及未保存的编辑器状态未覆盖。'),P('最终 PCB SHA-256：\n'+h[:32]+'\n'+h[32:]),T(['项目','基线 V3','最终 V3.1'],[['轨迹 / 过孔','2284 / 475','2107 / 489（新增14个有效地桥）'],['严格微短段 / 阈值边界','240 / 3','145 / 3；原243项全部建账'],['非标准整数角度段','600','537；逐项接入/侧接/绕障例外'],['器件 / 电气焊盘','151 / 469','151 / 469，脚网、型号、数值不变'],['制造资料','旧版本保留','Gerber、孔图、BOM、CPL重新生成']],[.35,.28,.37]),P('固定 ESP32、全部外接端子、三个电源模块、J16/J17/J19、板框、天线禁布区、六孔及外壳/按钮仓/开口/支撑。只交换同面 C35/R57 的位置并重布局部连接；没有增加器件、测试点或改变功能拓扑。'),P('主要限制：0.05Ω供电目标未达到；若干既有换层地桥距离仍偏长；热源合并模型与未知线束/接触/材料需要样机校准。未承诺绝对最优或量产性能。'))
add('02  整机原理与模块职责',T(['模块 / 位号','实际作用、源与返回','失效 / 边界'],[['GST120A24-P1M','24V/5A电源分配至控制PCB、板外驱动电源和K1线圈。','电机相电流、驱动输入电流与PCB控制电流分开。'],['CL1-42C +42CME04D','相线及编码器直接连接驱动器，延长线1.5m。','相线、驱动负极不得通过PCB信号地承担功率回流。'],['U1 / U11 / U33','U1产生5V；U11/U33分别产生6.5V限位触点电源。','CASE散热铜浮置且彼此分离，不能连GND。'],['四路SS-01GL2','使用COM/NC，约7.1mA/750Ω；两只备用不接入控制。','LO/RO阻止OPEN；LC/RC阻止CLOSE；允许退离。'],['U34～U40 / U42 / U45','滤波极性、方向联锁、授权锁存、脉冲门控和看门狗。','故障恢复本身不重新授权。'],['ESP32-S3 DevKitC-1 N8R8 v1.1','网页控制、配对、行程校准与传感器；固件未编写。','不能以离线逻辑模型替代应用状态机和通信租约。'],['SEN0228 / SET / BZ1','100kHzI2C光照、24V红灯自复位SET、内部5V有源蜂鸣器。','实际线长、SET灯电流/后端、USB线缆仍待确认。']],[.25,.44,.31]),P('五张理解表（功能块、电源/电流、信号/边沿、事件/故障、机械/外接线）在任何布局修改前完成。完整表、原始手册文件和来源哈希位于 evidence/baseline。光耦逻辑与系统地共用，不能称为安全电气隔离。'))
add('03  电源、电流与电压预算',P('控制路径 J1→F1→D1/D8/C7→U1；MCU路径 U1.3→D9→J19→U2.21，返回 U2.22→U1.2。保留保护和全部原有电容支路、J19电源断开功能。普通USB供电时拔开J19，保持板载与USB两路供电互斥。'),T(['20℃ / 35µm铜筛查','V3','V3.1'],[['中心线前向路径电阻',fnum(base['centreline_forward_ohm_20C'])+'Ω',fnum(new['centreline_forward_ohm_20C'])+'Ω'],['铜覆盖并集电阻（0.04mm网格）',fnum(sheet0)+'Ω',fnum(sheet1)+'Ω'],['GND返回（0.15mm网格）',fnum(base['sheet_ground_ohm_20C'],4)+'Ω',fnum(new['sheet_ground_ohm_20C'],4)+'Ω']],[.52,.24,.24]),P(f'独立铜面方法前向降低约{pct:.1f}%。两种方法具有不同偏差；中心线分段与理想焊盘接触会影响数值，铜并集网格包含对角/细颈离散误差，不能写成实测阻抗。0.2mm地栅格不能解析细颈，记录为RASTER_UNRESOLVED；实际铜连接由独立多边形及原生DRC确认。'),T(['供电场景 / 80℃铜','U2.21预算','剩余接触/纹波/瞬态余量'],[['0.5A、U1下界4.70V、D9筛查0.55V','3.993V','约0.313V，相对3.68V LDO筛查'],['0.8A、同样组合不利下界','3.899V','约−0.011V，相对3.91V；不保证']],[.49,.20,.31]),P('SGM2212为v1.1 DevKit实际LDO。手册压差定义在95%标称输出，不能当作精确3.3V稳压保证。模块精度和负载调整各−3%相加仅为敏感性，可能重复计入；二极管温度、跳帽/母座接触和瞬态须实测。0.5A为本轮核验包络，尚未验证实际峰值。'))
add('04  监督、器件规格与心跳契约',T(['关系','已核实的电气意图','需要实物/固件完成'],[['U41 / U44','3.3V与5V监督；U41阈值3.08V±2%，最低3.0184V；约200ms释放。','欠压波形、释放和局部3.3V最低值。'],['U45.3 EN','DevKit EN通过MCU_RESET_N控制看门狗使能；EN是输入。','EN复位时ENOUT快速禁止运动。'],['U45.6 WDI','GPIO47→R59→WDI；有效下降沿喂狗。','高电平保持不喂狗；控制任务停更必须停止下降沿。'],['U45.7/8 WDT_OK','WDO和ENOUT为允许组合的开漏输出，上拉后经U39清除U40。','170～230ms超时/启动延时；不会直接复位ESP32。'],['U40 CLR / CLK','D与PRE为高；故障清CLR，GPIO6经R5进入ARM_CLK，R35下拉。','健康恢复且GPIO6持续HIGH不再ARM，需新LOW→HIGH。'],['Q1～Q6 / 触点','已有栅极串阻/下拉、默认禁止、保持力路径和SET低侧驱动保留。','报警极性/驱动ENA脱机语义、CTR温度和SET灯电流。']],[.25,.44,.31]),P('手册以实际MPN及封装锁定；工作范围和门限使用推荐条件，不借绝对最大值证明正常可用。6.5V转换模块约1.4%轻载，低于厂家10～100%性能测试范围，电压、效率和纹波待实物校准。输入TVS钳位也不能替代异常电源瞬态实测。'),P('软件契约：GPIO47应由健康控制任务维护，≤50ms更新/≤100ms有效下降沿；应用停更、通信租约到期或状态异常时停喂狗。独立ISR/RMT自动心跳不得掩盖应用停更。TI TPS3431手册及锁定SHA在来源目录；尚未有运行固件。'))
add('05  启动、停止与故障恢复',T(['事件','脉冲 / 授权行为','保持力与恢复'],[['上电 / 欠压','监督未就绪时禁止；恢复需新ARM边沿。','健康驱动供电后按固件低速验证。'],['普通STOP','经硬件联锁禁止STEP并清授权。','ESTOP和POWER健康时保持力保留。'],['当前方向限位NC断开','OPEN方向LO/RO；CLOSE方向LC/RC清授权。','反方向限位断开允许退离，不能称全方向断线监控。'],['驱动ALM','按J17/驱动PA配置的实际极性清授权。','驱动内部故障时不能保证转矩。'],['EN复位 / WDI HIGH保持 / 心跳丢失','ENOUT独立禁止；无有效下降沿到超时后清RUN。','WDT不复位ESP；恢复仍需重新ARM。'],['急停','板外K1切驱动正电源；U24仅检测线圈命令。','掉电不能保证保持力；触点焊死/断开无反馈。'],['健康恢复但GPIO6仍HIGH','U40不会自动重锁存授权。','先LOW，再新的有效HIGH边沿。']],[.31,.39,.30]),P('16384个14输入静态向量、22个含实际GPIO6的方向/故障状态序列及170/200/230ms独立EN/WDI边沿模型全部通过。这些是离线事件模型，不覆盖传播延迟、触点弹跳、模拟欠压、转矩与位置。'),P('STEP契约≤100kHz、HIGH/LOW≥5µs；DIR设置≥10µs、ENA稳定≥5ms。230ms窗口在100kHz可容纳23000脉冲，不能称立即停止或认证安全功能。异步清除可能截短脉冲；位置失效时需重新回零/校准。'))
add('06  候选布局比较与淘汰理由',I('candidate_placement','A/B/C同尺度布局提案。B/C未通过硬门槛，不能把几何下界当作完成布线。'),T(['候选','局部工程评估','结果'],[['A 保留主要布局','内部原位置保留；C35/R57同面同方向交换并比较完整控制链。','采用，逐组真实铜核验。'],['B 看门狗外围迁移','U45/C35/R57/R58/R60移至133,88附近；42项院落/焊盘冲突，CASE占用约14.8mm²。','装配、间距和散热门槛淘汰。'],['C 监督/联锁联合迁移','有限0.5mm网格扫掠U39/C29；最少冲突位置仍碰C25和异网铜。','该候选族0合法站点，未采用。']],[.25,.52,.23]),P('RESET、两段心跳、POR、POWER_OK、ARM、RUN清除/反馈、STEP、DIR、HOLD及去耦同时列入CSV比较。C的几何下界虽缩短RUN_CLR等，PUL_GATED变长且装配冲突未解决；不能仅按总线长选C。本轮不证明其它所有联合布局均不可行。'))
add('07  第一组：电源与实际GND',I('comparison_power','同尺度底面，黄色高亮MCU供电相关铜；保护返回通道优先于整体加宽。'),P('最终主干仅在合法空间加宽，局部保留0.3～0.6mm逃线；J19固定导致较长通路，0.8～1.0mm目标未能铺满。中心线路径约112.42→114.00mm，电阻仍下降，说明线长不能替代供电截面和返回评估。'),P('曾完成更激进加宽试验，中心线筛查降至约0.169Ω，但固定空间采样发现RESET/ARM/I2C地参考损失，已淘汰。最终采用保护基线关键网络附近GND的方法；该失败方案和原因保留在工作备份及evidence/rejected_power_reference.json。'),P('新增14个地桥在两面都接入实际GND且回到J1.2；保留U1/U11/U33 CASE直接散热连接、输入保护和电容侧接。DIR附近0.8mm电源段退回0.4mm，恢复远端地角。铜图百分比不代替这项检查。'))
cap0=next(q for q in bp['decoupling_power_routes'] if q['from']=='U45.1');cap1=next(q for q in paths['decoupling_power_routes'] if q['from']=='U45.1')
add('08  第二组：C35、复位与授权',I('comparison_watchdog','仅C35/R57交换；U45、R58/R60保留位置和装配面。黄色为电源与GND，信号红色。'),T(['局部量','V3','V3.1'],[['U45.1→C35.1外露铜路径',fnum(cap0['trace_length_mm'])+'mm',fnum(cap1['trace_length_mm'])+'mm'],['C26→U36外露铜路径','0.602mm','0.602mm（保持）'],['C30→U40外露铜路径','0.775mm','0.775mm（保持）'],['RUN_CLR最近地最坏间隙','1.792mm','1.517mm；筛查值']],[.53,.235,.235]),P('外露铜路径扣除理想焊盘内部连接，不能与器件中心距离混用。C35电源侧接、CWD/R57、上拉R58、下拉R60及U45暴露焊盘GND均逐项复核。'),P('RESET局部新逃线处最近顶面GND约0.291→0.354mm，增加0.063mm；对面GND和全网最坏间隙不变。以U45.4为根的短地铜延伸维持连接。明确记录这处局部变化，未将最近距离统计写成零退化或EMC证明。'))
add('09  运动输出与外部接口',T(['完整通路','处理和连接核对','物理限制'],[['STEP','MCU_STEP→U37→STEP_LATCHED→U39→PUL_GATED→Q1→PUL−。','门控拓扑保留；任何异步截脉冲需位置恢复策略。'],['DIR / ENA / HOLD','Q2方向；Q3控制脱机；Q5在健康供电/急停条件下保留保持。','J16/J17服务跳帽固定，实际极性需驱动调试。'],['四限位','COM/NC返回经750Ω与光耦/RC/逻辑；触点供电6.5V。','每路约0.037W串阻功耗；旧33Ω发热支路不再存在。'],['I2C光照','U30 VCC/GND/SDA/SCL；Gravity端SDA/SCL/GND/VCC，线束必须交叉对应；D15与100Ω不变。','100kHz，实际电容/上升沿/VOL/抗扰验收；未知米数不保证。'],['SET / 蜂鸣器','J18:24V_COM、NO返回、灯A、灯K；NC空置绝缘。BZ1 KLJ-9650-5Y，壳内5V30mA。','灯20/50mA为建模假定；不代表所购按钮实测。']],[.23,.47,.30]),P('第三组运动输出通过核对后保留原几何，避免仅为了轻微整齐而改动快速边沿。第四组只清理FUNC_BTN_RET的局部路径。I2C试验的微小缩短导致地参考变化，最终维持原路，不做蛇形等长。'),P('外部PUL/DIR/ENA与各自共阳极5V返回成对布置；限位、I2C及面板线远离电机相线。驱动负极独立回电源分配点，不借PCB信号GND承担电机电源回流。'))
add('10  全板清理、角度与丝印',T(['原243项处置','数量','依据'],[[k,str(v),{'保留':'完整截面/原生接入','冗余覆盖删除':'完整包在其它同网显式铜内','共线合并':'整数区间铜覆盖并集相同','局部重布替换':'电源/逻辑/接口阶段核验','原生接入重建':'过孔中心接入规则保留'}[k]] for k,v in micro['original_action_counts'].items()],[.36,.12,.52]),P('严格小于0.15mm为240项，恰等于阈值3项；旧241是浮点边界口径。CSV逐项记录原UUID、网络、层、整数端点、宽度、用途、支路、处置、新UUID与检查。铜接入不存在“一删飞线为零就正确”的推断。'),P('最终148项：128焊盘/过孔接入、7宽度过渡、13足宽短拐角/侧接。537项整数非标准角度在JSON逐项记录接入对象、偏离量与附近异网间距；密集原有通道保留必要例外，不声称全部主干几何已绝对最优。零长度和完全重复段为零。'),I('silk_actual_positions','200处可见原生丝印文本：139个0°、61个90°（模180）。图采用实际位置/角度；完整大图在figures。'),P('C35/R57位号已跟随局部移位靠近元件。电压、极性和功能标注保留，原生丝印与焊盘检查通过；实际手工观察和器件遮挡仍须按装配图及样机核验。'))
add('11  顶面前后同尺度总览',I('comparison_top','铜形状来自实际填充，坐标和尺度一致；缺口、支路和过孔保持可对照。'),I('PCB_F_Cu','最终顶面独立大图；本报告缩略图不替代原生PCB/高分辨率铜图。'),P('CASE占据模块附近通道；优化同时保留GND实际连接。功能相关线采用已有清楚通道，对必要焊盘接入、跨层与支路不强制拉直。全板未整体拆线或交给自动布线代替比较。'))
add('12  底面前后同尺度总览',I('comparison_bottom','底层已有密集逻辑、阻容及驱动小器件；固定装配面后局部处理。'),I('PCB_B_Cu','最终底面图使用同一KiCad坐标投影，未镜像；制造CPL单独检查底面旋转和层归属。'),P('重复显式铜删除和共线合并仅改变必要对象集合；全部中途接入、焊盘与过孔重新独立检测。器件没有换面，CPL中C35/R57坐标随PCB更新。'))
add('13  三轮PCB、两轮一致性证据',T(['独立轮次','方法','最终结果'],[['PCB第1轮','原生DRC、未连接、脚网/工艺及固定对象','违规0，未连接0，针网/固定差异0。'],['PCB第2轮','Shapely实际铜/焊盘/孔槽/镀通；支路与回流','469针连接，短路0、开路0、孤立导体0；CASE逐面达到基线。'],['PCB第3轮','整机故障/恢复、装配工具、热/支撑/CAD','离线模型完成，动态实物项目未执行。'],['一致性1','11张SCH非线对象与线覆盖并集；XML网表与PCB','元件、针网、封装及数量差异0；库仅改命名。'],['一致性2','Gerbonara解析真实Gerber/Excellon/BOM/CPL','双面铜±3µm外差0；596孔、130SMT坐标一致。']],[.19,.43,.38]),P('原理图另完成三轮：配置ERC0；重新启用类别后31项绘图风格警告逐项处置（10四向共点、21单处全局标签）；实际器件/针网/监督契约核实；独立故障与边沿序列复核。没有把被忽略类别伪装成不存在。'),P('Gerber多边形量化对称差顶/底约0.236/0.392mm²，超过3µm的多余或缺失面积均为0。590镀孔+6非镀孔逐孔匹配，工具/坐标按0.001mm输出半量子核验。130SMT和21手工插件/模块分列；库存贴装库pin1/极性旋转须在下单预览验收。'),P('模型中的静态真值、源哈希和文件导出成功均不等于实物电气/EMC/停机性能。'))
rows=[[q['case'].replace('nominal','名义').replace('stress','较重').replace('adverse','不利').replace('mesh_2mm','2mm'),fnum(q['final']['max_pcb_C'],1),fnum(q['final']['max_pa12_C'],1),fnum(q['DevKit_final_C'],1),fnum(q['DevKit_final_C']-q['DevKit_baseline_C'],3)] for q in th['cases']]
add('14  六个热工况成对复算',T(['工况','PCB最高℃','PA12最高℃','DevKit等效℃','DevKit变化℃'],rows,[.36,.15,.16,.17,.16]),I('Thermal_cases','24℃、顶部朝上敞开、无强迫风，压力99/101/103kPa。自然对流与辐射仍存在。'),P('所有关键节点逐项前后比较保留在THERMAL_six_paired_cases.json。变化在约0.02℃内，明显小于网格、接触与参考物性误差，不能宣称降温。六工况能量收支相对残差小于0.01%，只证明计算自洽。'))
add('15  热源、网格与模型限制',I('Thermal_board_maps','实际铜覆盖、板框和孔槽进入热模型；热源与边界参数沿用V3，以保证成对比较。'),P('名义/较重总热约3.570/6.846W。较重工况 U2/U1/D9约2.306/1.038/0.254W，占总量约52.5%。加粗MCU铜主要改善压降；二极管压降降低会将损耗转移到LDO，不能直接宣称LDO降温。'),P('DevKit为合并单节点，esp32_3v3_A未独立进入热源函数；未私自修正算法。本次V3和V3.1均以同一算法重算。混合空气单节点和等效DevKit温度不能直接代入ESP32模块紧邻环境温度或芯片结温限制。N8R8无ECC的环境上限需实测核实。'),P('PA12参考k=0.22W/(mK)、ρ=1010kg/m³、cp=1690J/(kgK)；不利场景k=.192、cp=1170、对流0.7、敞口交换减半、接触导热降低。实际嘉立创PA12批次物性未知，参数保留可改。2mm/3mm网格PCB峰值差约1.3℃，比本次微小温差大。'))
add('16  裸板质量、重心与固定支撑',I('PCB_supports','估算只针对最终裸板材料和铜，不复用未经称重的101g整板预算。'),T(['量 / 支撑检查','最终V3.1'],[['裸板质量估算',fnum(mass['bare_board_estimate_g'],3)+'g；参考密度范围 '+fnum(mass['density_sensitivity_g'][0],2)+'～'+fnum(mass['density_sensitivity_g'][1],2)+'g'],['重心KiCad坐标',fnum(mass['centroid_KiCad_mm'][0],3)+', '+fnum(mass['centroid_KiCad_mm'][1],3)+'mm'],['六安装孔 / S1 / S2','位置、尺寸及接触区保留；底面侵入0。'],['S1 / S2扩大避让后剩余间距','0.323 /0.163mm；胶垫、插件尾脚公差需样机确认']],[.42,.58]),P('质量以实际铜覆盖并集、孔槽、FR4核心、镀孔铜与阻焊计算。密度、铜厚和镀层为可调参考，未称重。固定支撑不移动；最近支撑距离/梁条重力挠度仅为筛查，不覆盖器件质量、插拔力、跌落、螺丝预紧与垫片压缩。'))
add('17  外壳、插线与CAD回读',I('Enclosure_preview','FreeCAD可编辑模型与STEP/STL均回读；外壳半透明仅用于查看装配包络。'),T(['固定机械参数','值 / 结果'],[['主盒内长×宽 / 壁底厚','117.48×86.12mm /3mm'],['主盒外尺寸 /PCB上表面到敞口','123.48×92.12×52.1mm /30mm'],['四角及内支柱 /缓冲','5×5×15mm，六孔+S1/S2；2.5mm垫片'],['USB及按钮仓','两处15×8mm开口；按钮仓只向外伸、主壁只开接线口。'],['固体 / 干涉 / 固定几何','189个参考形体、13个导出回读有效；干涉0；主盒及5按钮盖布尔差体积0。']],[.45,.55]),P('主盒、仓、口和支撑与V3几何完全一致；更新组件包络和PCB来源哈希。SET后端采用已授权22×22×26mm宽松可换仓预算；USB插头25×9.5×6mm为参考包络。实物尺寸、打印收缩、攻丝深度、线束弯曲、工具与垫片适配仍需到货验收。'))
add('18  调试步骤、判据与未执行项',T(['步骤','测量 / 操作','验收边界'],[['1 无电检查','极性、NC线序、J16/J17/J19、CASE分别与GND绝缘、针网连续。','不得接电机功率负极到PCB信号返回。'],['2 限流控制板上电','记录U1输入/输出功率；U2.21对22及3.3V最低值/纹波。','实测总接触/纹波/瞬态小于预算余量；3.3V和监督保持有效。'],['3 固件与无负载驱动','初始化STEP/DIR/ARM/灯/心跳；测试STOP、EN和HIGH保持。','GPIO6持续HIGH健康恢复不能ARM；WDIHIGH不得喂狗。'],['4 四限位/报警/欠压','逐根NC断线，两方向检查；ALM、掉压、失联、应用停更。','方向选择符合意图；传播、触点弹跳和截脉冲实测。'],['5 急停及机械负载','K1真实分断、触点温升/冲击、保持与回零、停止距离。','线圈命令不是触点反馈；不能认证单通道安全功能。'],['6 热稳态与装配','待机/无线较重/灯蜂鸣器/启停至稳定；测LDO/ESP/U1/D9及局部空气。','模型误差校准；模块环境限制使用局部实测空气；USB/SET/垫片工具适配。']],[.23,.43,.34]),P('以上全部样机测量未执行；尚无固件或实物证据。完整线序、44针GPIO表和固件契约见“接线与固件契约.md”；逐项测量记录模板见“样机验收表.csv”。'),P('交付包含原生工程/本地库、候选指标/图、506个对象变更记录、243项处置、三轮PCB与原理图及两轮一致性证据、制造包、六热工况/CAD/质量模型、备份台账和重建脚本。双目录文件哈希一致及完整ZIP的CRC、成员、解压哈希由交付校验文件记录。'))
model={'revision':'V3.1','source_pcb_sha256':h,'pages':pages};(R/'document_model.json').write_text(json.dumps(model,ensure_ascii=False,indent=2),encoding='utf8')
md=['# CurtainDrive V3.1 工程设计与核验报告',f'生成：{datetime.datetime.now().isoformat(timespec="seconds")}。最终PCB SHA-256：`{h}`。']
for page in pages:
 md+=['','## '+page['title'],'']
 for b in page['blocks']:
  if b['type']=='paragraph':md += [b['text'],'']
  elif b['type']=='image':md += [f'![{b["caption"]}]({b["path"]})','']
  else:
   md += ['| '+' | '.join(b['header'])+' |','| '+' | '.join(['---']*len(b['header']))+' |']+['| '+' | '.join(str(v).replace('\n','<br>') for v in row)+' |' for row in b['rows']]+['']
(R/'工程设计与核验报告.md').write_text('\n'.join(md),encoding='utf8')
changes=['# V3→V3.1 完整变更与理由',f'最终PCB SHA-256：`{h}`。原V3及独立完整备份均保留。','',
'|类别|实施|工程理由/证据|','|---|---|---|',
'|局部布局|C35由(146,76.75)移至(148,74.25)；R57反向交换。均同面、0°。|缩短U45供电/去耦外露铜路径6.824→1.945mm；CWD/GND侧接保留。|',
'|电源|+5V_MCU_FEED /+5V_MCU局部开辟宽通道；固定J19保留。|中心线路阻0.238→0.218Ω；独立铜面0.251→0.225Ω。目标0.05Ω未达到。|',
'|地|新增14个两面连接的GND过孔；U45.4附近地铜延伸；DIR附近0.8mm电源段局部退至0.4mm。|保护已连通返回，恢复地角；RESET局部最近地距离+0.063mm单列审查。|',
'|CASE|六面CASE区边界适当扩展并保留U1细条。|三网与地分离，各面实际连通面积≥V3；非浮岛面积。|',
'|逻辑|逐组支路安全重布，RUN_CLR及监督局部主干清理。|真实铜/侧接/去耦/换层复核，非仅按端点飞线。|',
'|运动/I2C|核对后保持，未采用会损失地参考的美化试验。|快速边沿、保持力与完整STEP链优先。|',
'|外部接口|FUNC_BTN_RET局部清理。|端子、保护、串阻顺序、线序和GPIO不变。|',
'|全板|删完整显式铜覆盖的冗余，整数同宽共线合并。|轨迹2284→2107；243项逐项表，必要过孔接入恢复。|',
'|丝印/元数据|C35/R57位号靠近新位置；200处可见文本仅0/90°。项目/根SCH/PCB和库命名统一。|11页标题、PCB revision/DESIGN_REVISION、project变量均V3.1；铜几何与元数据变化分开。|',
'|制造/热/机械|全部从最终源更新；固定主盒/开口/支撑保持。|双面Gerber、596孔、130SMT/21手工；六热工况；裸板23.137g；CAD回读与布尔差一致。|',
'','506项具体对象差异见“全部铜与布局对象变更表.csv”；原243项见“微短段243项处置表.csv”；每次删除/新增UUID、坐标、网名和阶段SHA见evidence/accepted_patches与accepted_sequence。非标准角度/短段均有对象级记录；不声称已消除每个必要例外。',
'','未实施的范围扩展：移动J19、新电容/测试点、独立3.3V降压、替换模块、四层板、开槽、散热片或风扇。若0.5A包络的实测供电/温升/抗扰不合格，最小扩展与重新验收须另行决策。']
(R/'完整变更清单.md').write_text('\n'.join(changes),encoding='utf8')
# Actual native44pin map, including reserved pins, no invented GPIO assignment.
names={}
for p in (F/'project').glob('*.kicad_sch'):
 doc,lib,sy,*_=page_graph(p)
 if 'U2' in sy:
  for unit in kids(lib[one(sy['U2'],'lib_id')[1]],'symbol'):
   for pin in kids(unit,'pin'):names[one(pin,'number')[1]]=one(pin,'name')[1]
u2=next(p for p in ni['footprints'] if p['ref']=='U2');pins=[{'DevKit_pin':p['pin'],'native_pin_name':names[p['pin']],'PCB_net':p['net'],'status':'保留/未接' if p['net'].startswith('unconnected') else '实际连接'} for p in u2['pads'] if p['pin']]
assert len(pins)==44
with (R/'ESP32_44针实际GPIO脚网.csv').open('w',encoding='utf-8-sig',newline='') as file:
 wr=csv.DictWriter(file,fieldnames=list(pins[0]));wr.writeheader();wr.writerows(pins)
terminal={p['ref']:{a['pin']:a['net'] for a in p['pads'] if a['pin']} for p in ni['footprints'] if p['ref'] in ['J1','J3','J13','J14','J15','J18','J19','U18','U19','U20','U21','U22','U23','U24','U30']}
wire=['# 接线、控制意图与固件契约（未实施固件）','',f'依据V3.1原生针网，PCB SHA `{h}`。','', '|端子|实际针序（顺序不能按名称猜）|','|---|---|']+['|'+r+'|'+'；'.join(f'{k}: {v}' for k,v in p.items())+'|' for r,p in terminal.items()]+['',
'四路SS-01GL2使用COM/NC，LO/RO为OPEN边界，LC/RC为CLOSE边界；另一方向允许退离。NC打开不能区分触发和断线。两只备用不开第五/第六功能通道。',
'Gravity SEN0228的SDA/SCL/GND/VCC要与U30 VCC/GND/SDA/SCL逐针对应，使用3.3V；不能顺序直插。I2C100kHz，测总电容≤400pF、上升沿≤1µs和低电平，未知线长使用现场验收。',
'SET J18以自复位NO读取，NC未用端子绝缘。24V红灯电流20/50mA仅是建模包络；实物确认后填写。BZ1为内部5V有源KLJ-9650-5Y，30mA上界。',
'J16默认1–2接GND方向选择；J17默认1–2接3.3V报警选择。按实际驱动配置核验，CL1-42C报警PA4.01/PA4.31与ENA脱机极性须先低速/无机械负载测出；不得靠标签猜方向。',
'GST120A24-P1M控制支路给PCB；驱动正电源经板外K1 NO切断，驱动负极独立回源负极。相线及编码器接CL1-42C，不经过PCB。PUL/DIR/ENA采用板输出低侧与5V共阳极成对线束。',
'板外K1:Omron G2R-1-S DC24+P2RFZ-05-E，4COM、3NO、2NC未用、1/5线圈。电机5A支路0297005.WXMX+0FHM0001SXJ；线圈1A支路0287001.PXCN+0FHA0001ZXJ经急停NC控制K1.5与U24.1，K1.1独立回负极，SMBJ26CA线圈钳位。线圈约21.6mA/0.53W；容性输入冲击、真实分断/焊接与停止距离未验收。',
'GPIO初始化先禁止STEP、ARM保持LOW、灯和蜂鸣器按已定义默认值，再建立有效心跳、读取稳定监督和方向限位。新ARM LOW→HIGH后运动期间保持GPIO6 HIGH。STOP/故障/应用停更停止脉冲并清授权；恢复HIGH保持不得自动再ARM。',
'GPIO47心跳由应用控制任务维护，≤50ms更新/≤100ms有效下降沿；无独立硬件/ISR假健康。通信租约失效、状态陈旧或校准异常时停止喂狗。EN控制U45，不把WDT_OK接成直接ESP复位。',
'STEP≤100kHz、HIGH/LOW≥5µs；DIR setup≥10µs；ENA settle≥5ms。170～230ms看门狗时窗不是立即停机；任何位置不可信的截脉冲/掉电后回零或行程重新校准。',
'GPIO35–37供PSRAM，GPIO38板载RGB，GPIO19/20用于USB，GPIO0/3/45/46引导功能保留；实际44针CSV为权威针序。SET物理长按配对和行程校准的阈值/状态机尚未实现，不能伪称运行通过。',
'J19在使用普通USB供电前断开，避免双5V并联；带负载波形在U2.21对U2.22和本地3.3V量取。使用电源分配点承担驱动功率回流，布线远离电机相线。']
(R/'接线与固件契约.md').write_text('\n\n'.join(wire),encoding='utf8')
tests=[]
for category,nodes,items in [('电气供电','U1.1/2/3；U2.21/22；+3V3',[ '限流首次上电','待机和较重无线峰值/纹波','J19/USB供电互斥','U41/U44欠压与恢复' ]),('功能故障','STEP、ARM_CLK、WDI、WDT_OK、RUN_CLR_N、ENA',[ '普通STOP保持力','四路NC各自两方向断线','ALM极性及驱动配置','EN复位','WDI保持HIGH','丢失下降沿/应用停更/失联','故障解除GPIO6持续HIGH','新LOW→HIGH重新ARM','急停真实电源分断/停止距离','截脉冲位置无效后的回零' ]),('温升','LDO/ESP/U1/D9、局部空气、PA12',[ '名义99/101/103kPa稳态','較重负载和灯蜂鸣器持续','模型不利参数及网格/接触校准' ]),('装配','SET/USB/支柱/底面插件尾脚',[ 'SET灯电流和后端测量','USB插头及弯线插拔','2–3mm垫片压缩/螺丝啮合','全部端子螺丝刀/线束/返修','单通道K1启动冲击与触点温升' ])]:
 for t in items:tests.append({'类别':category,'试验':t,'测点/对象':nodes,'状态':'未执行','判据来源':'接线与固件契约.md /报告第18页 /POWER_voltage_and_resistance_review.json','实际仪器/环境':'','实测数据':'','通过/未通过':'','日期/人员':''})
for item in ['驱动启停/换向及邻近线束耦合','实际最长I2C/限位/按钮线的抗扰与边沿']:
 tests.append({'类别':'抗扰','试验':item,'测点/对象':'MCU_RESET_N/WDI/WDT_OK/PUL_GATED；SDA/SCL；NC/按钮输入','状态':'未执行','判据来源':'样机测量步骤与判据.md /接线与固件契约.md','实际仪器/环境':'','实测数据':'','通过/未通过':'','日期/人员':''})
with (R/'样机验收表.csv').open('w',encoding='utf-8-sig',newline='') as file:
 wr=csv.DictWriter(file,fieldnames=list(tests[0]));wr.writeheader();wr.writerows(tests)
print('Authored report model',len(pages),'pages;44pin contract,full changes and',len(tests),'physical tests unexecuted')
